variables:
  PRODUCTION_DEPLOY_USER: "project"
  PRODUCTION_DEPLOY_HOST: "xxx.xxx.xxx.xxx"
  PRODUCTION_DEPLOY_PATH: "xxxxxxxx"
  STAGING_DEPLOY_USER: "project"
  STAGING_DEPLOY_HOST: "xxx.xxx.xxx.xxx"
  STAGING_DEPLOY_PATH: "xxxxxxxx"
  GIT_STRATEGY: none
image: setos/deploy

stages:
  - deploy
  
deploy_production:
  stage: deploy
  environment:
    name: production
    url: https://xxxxxxxx.cz/
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_DEPLOY_KEY")
    - ssh-keyscan $PRODUCTION_DEPLOY_HOST > ~/.ssh/known_hosts
  script:
    - ssh $PRODUCTION_DEPLOY_USER@$PRODUCTION_DEPLOY_HOST 'cd '$PRODUCTION_DEPLOY_PATH'; git pull;'
    - ssh $PRODUCTION_DEPLOY_USER@$PRODUCTION_DEPLOY_HOST 'cd '$PRODUCTION_DEPLOY_PATH'; composer install;'
  tags:
    - docker
  only:
    - production

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://dev.xxxxxxx.cz
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_DEPLOY_KEY")
    - ssh-keyscan $STAGING_DEPLOY_HOST > ~/.ssh/known_hosts
  script:
    - ssh $STAGING_DEPLOY_USER@$STAGING_DEPLOY_HOST 'cd '$STAGING_DEPLOY_PATH'; git pull;'
    - ssh $STAGING_DEPLOY_USER@$STAGING_DEPLOY_HOST 'cd '$STAGING_DEPLOY_PATH'; composer install;'
  tags:
    - docker
  only:
    - staging
